services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    stdin_open: true
    tty: true
    working_dir: /app